### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Wupin** [TryHardDood/iZone#1]
Hi, I would like to report a bug that happens to me when I enter the command / Zmodem and has no zone so it gives me a wooden door into the inventory.     Google translator...

**Comment by benjaminforras** [comment]
Hello! This bug has been fixed today. https://github.com/TryHardDood/iZone/commit/b35f54749ccc1b1b23ef18d22aaedffaa4fc3be5
Please download the latest version of the plugin here: https://github.com/TryHardDood/iZone/releases/download/v8.0.14-b2/iZone.jar
