### ISSUE TITLE
Custom Titles in the GUI & Messages feature.

### ISSUE THREAD

**Issue by TheIntelloBox** [TryHardDood/iZone#2]
Hello,

All is in the title. 
Thanks. :D

**Comment by benjaminforras** [comment]
Hello,
Can you provide more info about the messages part?
And what do you mean by "Custom Titles in the GUI"

**Comment by TheIntelloBox** [comment]
Hello,

For example, when we create a zone there is a message in English. I want to translate it into French.
For the Titles in the GUI, there is in flags "Gamemode" for example and "Yes". I want to customize it.

Thanks !

**Comment by benjaminforras** [comment]
Oh I see. I'll see what I can do about it.

**Comment by TheIntelloBox** [comment]
Okay, thanks ! :)

**Comment by benjaminforras** [comment]
Updated.
Please translate this to French and I'll add it to the plugin: https://github.com/TryHardDood/iZone/blob/master/src/main/resources/messages_en.properties
